# Generated by Django 5.2.5 on 2025-09-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('acsessoris', 'Acsessoris'), ('footwear', 'Footwear'), ('protective gear', 'Protective Gear'), ('team kit', 'Team Kit'), ('match equipment', 'Match Equipment'), ('training equipment', 'Training Equipment'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('quantity_purchased', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
