# Generated by Django 5.2.5 on 2025-09-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('accessories', 'Accessories'), ('footwear', 'Footwear'), ('protective_gear', 'Protective Gear'), ('team_kit', 'Team Kit'), ('match_equipment', 'Match Equipment'), ('training_equipment', 'Training Equipment'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=30),
        ),
    ]
